# App Properties
bezkoder.app.jwtCookieName= bezkoder
bezkoder.app.jwtSecret= Z6y9F5mXKZz0b6Y7eJq2oM3yR8cP9nN4S1HkAqLwT0E=
bezkoder.app.jwtExpirationS= 3600

spring.security.user.name=disabled
spring.security.user.password=disabled


services.application.url=8080
